apiName: "TreeSoftware API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../workshop-client/

server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080
